import {StyleSheet} from 'react-native';
import {theme} from '../theme/theme';

const {colors, font, fontWeight, lineHeight, radius, spacing} = theme;

export const styles = StyleSheet.create({
  filterPanel: {
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderColor: colors.border,
    borderTopWidth: 1,
    paddingBottom: spacing.lg,
    paddingHorizontal: spacing.screen,
    paddingTop: spacing.lg,
  },
  filterBar: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
  },
  filterToggle: {
    alignItems: 'center',
    backgroundColor: colors.textPrimary,
    borderRadius: radius.sm,
    flexDirection: 'row',
    gap: spacing.sm + 1,
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.md + 1,
  },
  filterToggleText: {
    color: colors.surface,
    fontSize: font.sm,
    fontWeight: fontWeight.strong,
  },
  filterCountBadge: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: radius.pill,
    justifyContent: 'center',
    minWidth: spacing.section,
    paddingHorizontal: spacing.xs + 1,
  },
  filterCountText: {
    color: colors.textPrimary,
    fontSize: font.xxs,
    fontWeight: fontWeight.strong,
  },
  activeFilters: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    paddingRight: spacing.md,
  },
  activeFilterChip: {
    alignItems: 'center',
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.borderStrong,
    borderRadius: radius.pill,
    borderWidth: 1,
    flexDirection: 'row',
    gap: spacing.sm + 1,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm + 1,
  },
  activeFilterText: {
    color: colors.textBody,
    fontSize: font.sm,
    fontWeight: fontWeight.strong,
    maxWidth: 110,
  },
  activeFilterRemove: {
    color: colors.textSecondary,
    fontSize: font.xs,
    fontWeight: fontWeight.strong,
  },
  noFiltersText: {
    color: colors.textSecondary,
    fontSize: font.sm,
  },
  clearInlineButton: {
    paddingHorizontal: spacing.xxs,
    paddingVertical: spacing.md,
  },
  clearInlineText: {
    color: colors.primary,
    fontSize: font.sm,
    fontWeight: fontWeight.strong,
  },
  filterSheet: {
    borderTopWidth: 1,
    borderColor: colors.borderSoft,
    marginTop: spacing.xl,
    paddingTop: spacing.lg,
  },
  filterGroup: {
    marginTop: spacing.md,
  },
  filterLabel: {
    color: colors.textSecondary,
    fontSize: font.xs,
    fontWeight: fontWeight.strong,
    marginBottom: spacing.md,
    textTransform: 'uppercase',
  },
  filterOptions: {
    flexDirection: 'row',
    gap: spacing.md,
    paddingRight: spacing.screen,
  },
  filterChip: {
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.borderStrong,
    borderRadius: radius.pill,
    borderWidth: 1,
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.md,
  },
  filterChipText: {
    color: colors.textBody,
    fontSize: font.sm,
    fontWeight: fontWeight.strong,
  },
  filterError: {
    color: colors.danger,
    fontSize: font.sm,
    marginTop: spacing.lg,
  },
  card: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.sm,
    borderWidth: 1,
    elevation: 1,
    marginBottom: spacing.lg,
    padding: spacing.screen,
    shadowColor: colors.shadow,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.04,
    shadowRadius: 3,
  },
  cardPressed: {
    borderColor: colors.primarySoft,
  },
  cardHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: spacing.xl,
    justifyContent: 'space-between',
  },
  cardTitleGroup: {
    flex: 1,
  },
  cardTitle: {
    color: colors.textPrimary,
    fontSize: font.xl,
    fontWeight: fontWeight.strong,
    lineHeight: lineHeight.cardTitle,
  },
  taskId: {
    color: colors.textMuted,
    fontSize: font.xs,
    fontWeight: fontWeight.strong,
    marginTop: spacing.xs,
  },
  openDetailText: {
    color: colors.primary,
    fontSize: font.xs,
    fontWeight: fontWeight.strong,
    paddingTop: spacing.xxs,
  },
  description: {
    color: colors.textDescription,
    fontSize: font.md,
    lineHeight: lineHeight.sm,
    marginTop: spacing.md,
  },
  badges: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
    marginTop: spacing.xl,
  },
  badge: {
    borderRadius: radius.pill,
    borderWidth: 1,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.xs + 1,
  },
  badgeText: {
    fontSize: font.xs,
    fontWeight: fontWeight.strong,
  },
  centerState: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    padding: spacing.state,
  },
  emptyState: {
    alignItems: 'center',
    padding: spacing.state,
  },
  emptyTitle: {
    color: colors.textPrimary,
    fontSize: font.xxl,
    fontWeight: fontWeight.strong,
  },
  stateText: {
    color: colors.textSecondary,
    fontSize: font.lg,
    lineHeight: lineHeight.body,
    marginTop: spacing.lg,
    textAlign: 'center',
  },
  errorTitle: {
    color: colors.danger,
    fontSize: font.xxl + 1,
    fontWeight: fontWeight.strong,
  },
  retryButton: {
    backgroundColor: colors.primary,
    borderRadius: radius.sm,
    marginTop: spacing.section,
    paddingHorizontal: spacing.screen,
    paddingVertical: spacing.lg,
  },
  retryText: {
    color: colors.surface,
    fontSize: font.md,
    fontWeight: fontWeight.strong,
  },
});
